apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - protocol: http
      port: 8200       
      targetPort: 8200 
      nodePort: 30001 
